# Generated by Django 4.2 on 2023-04-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_id", models.UUIDField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("addresses", models.JSONField()),
                ("time_remaining", models.TimeField()),
            ],
        ),
    ]
